/***********************************************************************

main.script

This is the main script that is loaded before any level scripts load.

***********************************************************************/

// base defines and util functions

#include "scripts/defs.script"
#include "scripts/events.script"
#include "scripts/util.script"

#include "scripts/default.script"

#include "scripts/teams/base.script"

#include "scripts/misc/objective_manager.script"
#include "scripts/misc/objective.script"
#include "scripts/misc/firesupport_marker.script"

// tasks
#include "scripts/tasks/task.script"
#include "scripts/tasks/task_manager.script"

// player
#include "scripts/player/player.script"

// base scripts
#include "scripts/weapons/base.script"
#include "scripts/deployables/firesupportstate.script"
#include "scripts/deployables/base.script"
#include "scripts/structures/base.script"
#include "scripts/vehicles/base.script"

#include "scripts/misc/waypoint.script"
#include "scripts/misc/direction_marker.script"

// weapons
#include "scripts/weapons/misc.script"
#include "scripts/weapons/clipweapon.script"
#include "scripts/weapons/fists.script"
#include "scripts/weapons/grenade.script"
#include "scripts/weapons/shotgun.script"
#include "scripts/weapons/pistol.script"
#include "scripts/weapons/pistol_akimbo.script"
#include "scripts/weapons/blaster.script"
#include "scripts/weapons/sniperrifle.script"
#include "scripts/weapons/railgun.script"
#include "scripts/weapons/machinepistol.script"
#include "scripts/weapons/lightningpistol.script"
#include "scripts/weapons/law.script"
#include "scripts/weapons/assaultrifle.script"
#include "scripts/weapons/assaultrifle_gren.script"
#include "scripts/weapons/assaultrifle_scope.script"
#include "scripts/weapons/gpmg.script"
#include "scripts/weapons/hyperblaster.script"
#include "scripts/weapons/lacerator.script"
#include "scripts/weapons/lacerator_gren.script"
#include "scripts/weapons/lacerator_scope.script"
#include "scripts/weapons/obliterator.script"
#include "scripts/weapons/nailgun.script"
#include "scripts/weapons/dummy.script"

// tools
#include "scripts/tools/targeting.script"
#include "scripts/tools/binoculars.script"
#include "scripts/tools/deploytool.script"
#include "scripts/tools/pliers.script"
#include "scripts/tools/trinoculars.script"
#include "scripts/tools/defibrillator.script"
#include "scripts/tools/repair_drone.script"
#include "scripts/tools/force_shield.script"
#include "scripts/tools/spike_meditech.script"

// items
#include "scripts/items/hecharge.script"
#include "scripts/items/smoke_grenade.script"
#include "scripts/items/plasmacharge.script"
#include "scripts/items/landmine.script"
#include "scripts/items/supplypack.script"
#include "scripts/items/third_eye.script"
#include "scripts/items/carryable_item.script"
#include "scripts/items/flyerhive.script"
#include "scripts/items/healthpack.script"

// projectiles
#include "scripts/projectiles/missile.script"
#include "scripts/projectiles/grenade.script" 
#include "scripts/projectiles/armable.script"
#include "scripts/projectiles/homingmissile.script"
#include "scripts/projectiles/targetedmissile.script"
#include "scripts/projectiles/landmine.script"
#include "scripts/projectiles/charge.script"
#include "scripts/projectiles/emp.script"
#include "scripts/projectiles/ssm.script"
#include "scripts/projectiles/scud.script"
#include "scripts/projectiles/ssg.script"
#include "scripts/projectiles/teleporter.script"
#include "scripts/projectiles/airstrike_marker.script"
#include "scripts/projectiles/supply_marker.script"

// tools (that are dependent on their projectiles)
#include "scripts/tools/teleporter.script"

// structures
#include "scripts/structures/cc.script"
#include "scripts/structures/domihub.script"

// deployables
#include "scripts/deployables/artillery.script"
#include "scripts/deployables/turret.script"
#include "scripts/deployables/antiarmour.script"
#include "scripts/deployables/antipersonnel.script"
#include "scripts/deployables/antissg.script"
#include "scripts/deployables/deployzone.script"
#include "scripts/deployables/fielddrop.script"
#include "scripts/deployables/intelligence.script"
#include "scripts/deployables/ssm.script"
#include "scripts/deployables/ssg.script"
#include "scripts/deployables/plasmamortar.script"
#include "scripts/deployables/autodeployer.script"
#include "scripts/deployables/mount.script"
#include "scripts/deployables/shield_generator.script"
#include "scripts/deployables/basedefence.script"
#include "scripts/deployables/drop_caller.script"

// vehicles
#include "scripts/vehicles/anansi.script"
#include "scripts/vehicles/badger.script"
#include "scripts/vehicles/vampire.script"
#include "scripts/vehicles/violator.script"
#include "scripts/vehicles/bumblebee.script"
#include "scripts/vehicles/desecrator.script"
#include "scripts/vehicles/goliath.script"
#include "scripts/vehicles/hog.script"
#include "scripts/vehicles/hornet.script"
#include "scripts/vehicles/husky.script"
#include "scripts/vehicles/magog.script"
#include "scripts/vehicles/jotun.script"
#include "scripts/vehicles/mcp.script"
#include "scripts/vehicles/titan.script"
#include "scripts/vehicles/trojan.script"
#include "scripts/vehicles/icarus.script"
#include "scripts/vehicles/strogg_drop.script"
#include "scripts/vehicles/platypus.script"
#include "scripts/vehicles/weapons/base.script"
#include "scripts/vehicles/weapons/gpmg.script"
#include "scripts/vehicles/weapons/gpmg_twin.script"
#include "scripts/vehicles/weapons/rockets.script"
#include "scripts/vehicles/weapons/sbc.script"
#include "scripts/vehicles/weapons/plasmacannon.script"
#include "scripts/vehicles/weapons/cannon_twin.script"
#include "scripts/vehicles/weapons/law.script"
#include "scripts/vehicles/weapons/antiair.script"
#include "scripts/vehicles/weapons/stroybomb.script"
#include "scripts/vehicles/parts/base.script"
#include "scripts/vehicles/cockpits/basic.script"
#include "scripts/vehicles/cockpits/strogg.script"
#include "scripts/vehicles/cockpits/badger.script"
#include "scripts/vehicles/cockpits/icarus.script"
#include "scripts/vehicles/cockpits/anansi.script"
#include "scripts/vehicles/cockpits/trojan.script"
#include "scripts/vehicles/cockpits/mcp.script"
#include "scripts/vehicles/cockpits/platypus.script"
#include "scripts/vehicles/cockpits/hog.script"
#include "scripts/vehicles/cockpits/desecrator.script"
#include "scripts/vehicles/cockpits/gpmg.script"
#include "scripts/vehicles/cockpits/gatling.script"
#include "scripts/vehicles/cockpits/husky.script"

// misc
#include "scripts/misc/doors.script"
#include "scripts/misc/supply_crate.script"
#include "scripts/misc/animtest.script"
#include "scripts/misc/spawn_master.script"
#include "scripts/projectiles/decoy.script"
#include "scripts/misc/auto_respawn.script"
#include "scripts/misc/atmosphere.script"
#include "scripts/misc/rules.script"
#include "scripts/misc/item_capturepoint.script"
#include "scripts/misc/flag.script"
#include "scripts/misc/lightning.script"
#include "scripts/misc/mcp_marker.script"
#include "scripts/misc/parachute.script"
#include "scripts/misc/capturable_spawn.script"
#include "scripts/misc/maskeditor.script"
#include "scripts/misc/mcp_trigger.script"
#include "scripts/misc/bot_mcp_trigger.script"
#include "scripts/misc/syncedeffect.script"
#include "scripts/misc/noplant.script"
#include "scripts/misc/particle_trigger.script"

// screenshot placement stuff
#include "scripts/placement/player.script"
#include "scripts/placement/weapon.script"
#include "scripts/placement/vehicle.script"
#include "scripts/placement/rotator.script"

// teams!
#include "scripts/teams/gdf.script"
#include "scripts/teams/strogg.script"

// map objectives
#include "scripts/maps/generic/constructible_objective.script"
#include "scripts/maps/generic/destructible_objective.script"
#include "scripts/maps/generic/hackable_objective.script"
#include "scripts/maps/generic/zappor.script"
#include "scripts/maps/generic/scud_trigger.script"
#include "scripts/maps/generic/navmodule.script"

#include "scripts/maps/island/console.script"
#include "scripts/maps/slipgate/effects.script"

// generic map stuff
#include "scripts/maps/generic/jumppad.script"
#include "scripts/maps/generic/towers.script"


// context sensitive stuff
#include "scripts/player/player_context.script"

// maps
#include "scripts/maps/base.script"
#include "scripts/maps/default.script"
#include "scripts/maps/ark.script"
#include "scripts/maps/area22.script"
#include "scripts/maps/canyon.script"
#include "scripts/maps/dm.script"
#include "scripts/maps/outskirts.script"
#include "scripts/maps/island.script"
#include "scripts/maps/quarry.script"
#include "scripts/maps/refinery.script"
#include "scripts/maps/salvage.script"
#include "scripts/maps/sewer.script"
#include "scripts/maps/slipgate.script"
#include "scripts/maps/valley.script"
#include "scripts/maps/vehicletrack.script"
#include "scripts/maps/volcano.script"
#include "scripts/maps/screenshots/empty.script"
#include "scripts/maps/bottest2.script"
#include "scripts/maps/routeconstraint.script"
#include "scripts/maps/misctestmaps.script"
#include "scripts/map.script"

void game_main() {
	SetupColors();

	vec3_up_z		= 1.f;
	vec3_down_z		= -1.f;

	wstr_empty		= sys.toWStr( "" );
	invalid_handle	= sys.stringToHandle( "FFFFFFFF" );

	g_ammoStroyent				= GetAmmoType( "stroyent" );
	g_ammoStroyentPacket		= GetAmmoType( "stroyent_packet" );
	g_ammoMachinePistol			= GetAmmoType( "machinepistol" );
	g_ammoAssaultRifle			= GetAmmoType( "assaultrifle" );
	g_ammoGrenade				= GetAmmoType( "grenade" );
	g_ammoShotgun				= GetAmmoType( "shotgun" );
	g_ammoSniperRifle			= GetAmmoType( "sniperrifle" );
	g_ammoPistol				= GetAmmoType( "pistol" );
	g_ammoRocketLauncher		= GetAmmoType( "rocketlauncher" );
	g_ammoGPMG					= GetAmmoType( "gpmg" );

	g_proficiencyLightWeapons	= GetProficiencyType( "weapon_handling" );

	g_proficiencyBattleSense	= GetProficiencyType( "battlesense" );

	g_proficiencyFieldOps		= GetProficiencyType( "fieldops" );
	g_proficiencyMedic			= GetProficiencyType( "medic" );
	g_proficiencyEngineer		= GetProficiencyType( "engineer" );
	g_proficiencyCovertOps		= GetProficiencyType( "covertops" );
	g_proficiencySoldier		= GetProficiencyType( "soldier" );

	g_proficiencyOppressor		= GetProficiencyType( "fieldops" );
	g_proficiencyTechnician		= GetProficiencyType( "medic" );
	g_proficiencyConstructor	= GetProficiencyType( "engineer" );
	g_proficiencyInfiltrator	= GetProficiencyType( "covertops" );
	g_proficiencyAggressor		= GetProficiencyType( "soldier" );

	g_proficiencyVehicle		= GetProficiencyType( "vehicle" );

	g_playerClassSoldier		= GetPlayerClass( "soldier" );
	g_playerClassMedic			= GetPlayerClass( "medic" );
	g_playerClassCovertOps		= GetPlayerClass( "covertops" );
	g_playerClassEngineer		= GetPlayerClass( "engineer" );
	g_playerClassFieldOps		= GetPlayerClass( "fieldops" );

	g_playerClassAggressor		= GetPlayerClass( "aggressor" );
	g_playerClassTechnician		= GetPlayerClass( "technician" );
	g_playerClassConstructor	= GetPlayerClass( "constructor" );
	g_playerClassOppressor		= GetPlayerClass( "oppressor" );
	g_playerClassInfiltrator	= GetPlayerClass( "infiltrator" );

	g_disableVehicleSpawns		= sys.getCVar( "g_disableVehicleSpawns", "0" );
	pm_thirdperson				= sys.getCVar( "pm_thirdperson", "0" );
	bse_projectileEffect		= sys.getCVar( "bse_projectileEffect", "" );
	g_maxProficiency			= sys.getCVar( "g_maxProficiency", "" );
	g_friendlyColor				= sys.getCVar( "g_friendlyColor", "0 1 0 1" );
	g_neutralColor				= sys.getCVar( "g_neutralColor", "0.75 0.75 0.75" );
	g_enemyColor				= sys.getCVar( "g_enemyColor", "1 0 0 1" );
	g_fasterSpawn				= sys.getCVar( "g_fasterSpawn", "1" );
	si_rules					= sys.getCVar( "si_rules", "" );
	g_noVehicleSpawnInvulnerability	= sys.getCVar( "g_noVehicleSpawnInvulnerability", "" );
	g_objectiveDecayTime		= sys.getCVar( "g_objectiveDecayTime", "5" );
	g_aptWarning				= sys.getCVar( "g_aptWarning", "3" );

	g_drawMineIcons				= sys.getCVar( "g_drawMineIcons", "" );
	g_allowMineIcons			= sys.getCVar( "g_allowMineIcons", "" );
	g_mineIconSize				= sys.getCVar( "g_mineIconSize", "" );
	g_mineIconAlphaScale		= sys.getCVar( "g_mineIconAlphaScale", "" );


	g_locStr_Destroyed			= sys.localizeString( "game/destroyed" );
	g_locStr_Disabled			= sys.localizeString( "game/disabled" );
	g_locStr_Range 				= sys.localizeString( "game/range_text" );
	g_locStr_Meters 			= sys.localizeString( "game/meters" );
	g_locStr_Capture 			= sys.localizeString( "game/spawns/capture" );
	g_locStr_SpawnHost 			= sys.localizeString( "game/misc/spawn_host" );
	g_locStr_Supplies 			= sys.localizeString( "game/supplies" );
	g_locStr_Unconscious 		= sys.localizeString( "game/unconscious" );
	g_locStr_Dead 				= sys.localizeString( "game/dead" );
	g_locStr_Hacking 			= sys.localizeString( "game/prog_bar/hacking" );
	g_locStr_Arming 			= sys.localizeString( "game/prog_bar/arming" );
	g_locStr_Disarming			= sys.localizeString( "game/prog_bar/disarming" );
	g_locStr_Repairing 			= sys.localizeString( "game/prog_bar/repairing" );
	g_locStr_Constructing 		= sys.localizeString( "game/prog_bar/constructing" );
	g_locStr_Capturing 			= sys.localizeString( "game/prog_bar/capturing" );
	g_locStr_Liberating			= sys.localizeString( "game/prog_bar/liberating" );
	g_locStr_Implanting			= sys.localizeString( "game/prog_bar/implanting" );
	g_locStr_Disguising			= sys.localizeString( "game/prog_bar/disguising" );
	g_locStr_Spotting			= sys.localizeString( "game/prog_bar/spotting" );
	g_locStr_Reviving			= sys.localizeString( "game/prog_bar/reviving" );
	g_locStr_Charge 			= sys.localizeString( "game/charge" );
	g_locStr_Landmine 			= sys.localizeString( "game/landmine" );
	g_locStr_Tripmine 			= sys.localizeString( "game/tripmine" );
	g_locStr_Proxmine 			= sys.localizeString( "game/prox_mine" );
	g_locStr_Scrambler			= sys.localizeString( "game/scrambler_trap" );
	g_locStr_DoNotOwnTerritory 	= sys.localizeString( "game/guis/tools/not_own_territory" );
	g_locStr_NoCharge		 	= sys.localizeString( "game/guis/tools/no_charge" );
	g_locStr_Dismantle 			= sys.localizeString( "game/guis/tools/dismantle" );
	g_locStr_Drone 				= sys.localizeString( "game/vec/drone" );
	g_locStr_Scud 				= sys.localizeString( "game/vec/mcp/scud" );
	g_locStr_Airstrike 			= sys.localizeString( "game/airstrike" );
	g_locStr_Completed			= sys.localizeString( "game/completed" );
	g_locStr_Objective			= sys.localizeString( "game/objective" );
	g_locStr_UnarmedTripmine	= sys.localizeString( "game/unarmedtripmine" );
	g_locStr_UnarmedProxymine	= sys.localizeString( "game/unarmedproxmine" );
	g_locStr_SelfArmingTripmine	= sys.localizeString( "game/selfarmingtripmine" );
	g_locStr_SelfArmingProxymine	= sys.localizeString( "game/selfarmingproxmine" );
	g_locStr_TeleportBeacon		= sys.localizeString( "game/teleport_beacon" );
	g_locStr_BadObjective		= sys.localizeString( "game/bad_objective" );
	g_locStr_Someone			= sys.localizeString( "game/someone" );
}

void game_shutdown() {
}
