#include <quickchat/common.include>

// MEDIC CHATS ////////////////////////////////////////////

quickChatDef gdf/botchat/generic/holdonimamedic {
	_chat( "gdf/botchat/generic/imamedic", "", "team", BOT_TYPE_MEDIC_ACK, "" )
}

quickChatDef gdf/botchat/generic/medicenroute {
	_chat( "gdf/botchat/generic/medicenroute", "", "team", BOT_TYPE_MEDIC_ACK, "" )
}

quickChatDef gdf/botchat/generic/tkrevive {
	_chat( "gdf/botchat/generic/tkrevive", "", "team", BOT_TYPE_TK_REVIVE, "" )
}

// ESCORT CHATS ////////////////////////////////////////

quickChatDef gdf/botchat/generic/youlead {
	_chat( "gdf/botchat/generic/youlead", "", "team", BOT_TYPE_LETS_GO, "" )
}

quickChatDef gdf/botchat/generic/gotyourback {
	_chat( "gdf/botchat/generic/gotyourback", "", "team", BOT_TYPE_LETS_GO, "" )
}

quickChatDef gdf/botchat/generic/leadway {
	_chat( "gdf/botchat/generic/leadway", "", "team", BOT_TYPE_LETS_GO, "" )
}

quickChatDef gdf/botchat/generic/whereto {
	_chat( "gdf/botchat/generic/whereto", "", "team", BOT_TYPE_LETS_GO, "" )
}

// ENGINEER CHATS ///////////////////////////////////

quickChatDef gdf/botchat/generic/vehicle/letmerepair {
	_chat( "gdf/botchat/generic/vehicle/letmerepair", "", "team", BOT_TYPE_WILL_FIX_RIDE, "" )
}

quickChatDef gdf/botchat/generic/vehicle/iwillfixride {
	_chat( "gdf/botchat/generic/vehicle/iwillfixride", "", "team", BOT_TYPE_WILL_FIX_RIDE, "" )
}


quickChatDef gdf/botchat/generic/vehicle/stopiwillfixride {
	_chat( "gdf/botchat/generic/vehicle/stopiwillfixride", "", "team", BOT_TYPE_STOP_WILL_FIX_RIDE, "" )
}

// AMMO CHAT ////////////////////////////////////////

quickChatDef gdf/botchat/generic/gotammo {
	_chat( "gdf/botchat/generic/gotammo", "", "team", BOT_TYPE_AMMO_ACK, "" )
}


// GENERIC OBJ CHATS //////////////////////////////////
quickChatDef gdf/botchat/objectives/planthecharge {
	_chat( "gdf/botchat/objectives/explosives/plant", "", "team", BOT_TYPE_GENERIC_PLANT, "" )
}





// GENERIC CHATS //////////////////////////////////////
quickChatDef gdf/botchat/generic/needalift {
	_chat( "gdf/botchat/generic/needalift", "", "team", BOT_TYPE_NEED_LIFT, "" )
}

quickChatDef gdf/botchat/generic/needaride {
	_chat( "gdf/botchat/generic/needaride", "", "team", BOT_TYPE_NEED_LIFT, "" )
}






